env:
  browser: true
  es2021: true
  jest: true
  cypress/globals: true
extends:
  - airbnb-base
  - plugin:cypress/recommended
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: latest
  sourceType: module
settings:
  import/resolver:
    node:
      extensions: ['.json', '.mjs', '.js', '.jsx', '.ts', '.tsx', '.d.ts']
    typescript: {}
plugins:
  - '@typescript-eslint'
  - cypress
rules:
  max-len:
    - error
    - 120
  no-console:
    - error
  newline-per-chained-call:
    - error
    - ignoreChainWithDepth: 2
  arrow-parens:
    - warn
    - as-needed
  no-restricted-syntax: off
  arrow-body-style: off
  import/extensions:
    - error
    - ignorePackages
    - js: always
      ts: never
      tsx: never
overrides:
  - files:
    - '*.d.ts'
    rules:
      no-undef: off
      no-unused-vars: off
